### ISSUE TITLE
Cross compile MacOS arm64 binaries on GH actions

### ISSUE THREAD

**Issue by bjia56** [yifeikong/curl-impersonate#21]
This should make building new curl-impersonate versions fully self-contained within the repo's CI.

Stretch goal (optional) could be to make universal2 binaries from x86_64 + arm64 binaries.

**Comment by yifeikong** [comment]
Useful links: https://stackoverflow.com/questions/65361672/build-apple-silicon-binary-on-intel-machine

**Comment by yifeikong** [comment]
Thanks to GitHub, we already have native arm64 build.
