### ISSUE TITLE
Native Node.js addon

### ISSUE THREAD

**Issue by sussyGaymer** [yifeikong/curl-impersonate#29]
I was wondering if it was possible for you to integrate libcurl-impersonate into a native [Node.js addon](https://nodejs.org/api/addons.html) so it works in JS out-of-the-box, without the long and tedious process of building [node-libcurl](https://github.com/JCMais/node-libcurl) with the impersonate patch.
What I'm suggesting is a fork of node-libcurl because  I feel like that would take a lot less work than creating a new thing from scratch. While I do understand there are a couple of forks which do that, they are all unmaintained and largely out of date. This repository seems somewhat alive so I hope it won't be an issue keeping it alive. (An occasional pull from upstream should be all of the maintenance it needs.)
I'm not very familiar with the development ecosystem of c++ and such so I'm afraid I won't be of much help, but logically it shouldn't be that big of a deal, right? Surely we can just replace which `curl` it uses in it's `deps`. (I understand it may not be this simple, but I really need a reliable impersonate library in Node. Thanks in advance!)

**Comment by sussyGaymer** [comment]
> While I do understand there are a couple of forks which do that, they are all unmaintained and largely out of date.

Yes, I acknowledged the other fork(s) but as I mentioned, it hasn't been updated for **2 years**. Not sure how to feel about that but I'm definitely not using something like that.

The sole reason I proposed this was to get a regularly maintained lib that works and is up to date. If nobody is willing to do something like this, I'll probably go and bother the original author of the fork you linked above since it seems like the most promising thing.

**Comment by yifeikong** [comment]
Look at this one, it's quite new, updated 4 month ago. https://github.com/ycq0125/node-libcurl

**Comment by sussyGaymer** [comment]
I stumbled upon that package as well during my research, but it looked sketchy and unmaintained. I still decided to give it a try and got some build errors when installing it that I'm not willing to look into further since the only error I see is `MSBuild.exe failed with exit code: 1` which is extremely frustrating.

I'll try to replace the libcurl package of `node-libcurl` or even go as far as forking the package and see where that gets me. Hoping for the best.

**Comment by sussyGaymer** [comment]
Tried that a couple days ago but it didn't work correctly if I remember correctly. I'll try some other things in the meantime. I hope you understand me making this issue was a last resort after nothing else worked.

**Comment by yifeikong** [comment]
Which platform are you on? Windows?

**Comment by sussyGaymer** [comment]
Windows 10. Specifically 10.0.19045.3693.

**Comment by yifeikong** [comment]
I guess it's a little more diffcult for you to use the environment variable trick. But here are a few general tips:

1. You can download the window dll, from this fork's release page.
2. Unlike on Linux, you don't need to `patchelf` or whatever.
3. Install node-libcurl, find which libcurl.dll it's using, replace it with the dll above.
4. Setup envionment variable the Windows way, depending on your shell or app.

**Comment by bonald** [comment]
I just do this :)

apt install build-essential pkg-config cmake ninja-build curl autoconf automake libtool golang-go unzip python-is-python3 2to3 libcurl4-openssl-dev build-essential
git clone https://github.com/yifeikong/curl-impersonate.git
cd curl-impersonate
mkdir build && cd build
../configure
make chrome-build
make chrome-install
ldconfig
rm /usr/local/lib/libcurl.so
ln -s /usr/local/lib/libcurl-impersonate-chrome.so.4.8.0 /usr/local/lib/libcurl.so
rm /usr/bin/curl-config
ln -s /usr/local/bin/curl-impersonate-chrome-config /usr/bin/curl-config
echo "/usr/local/lib/libcurl-impersonate-chrome.so" >> /etc/ld.so.preload
ldconfig

cd your-app
rm package-lock*
npm install node-libcurl --build-from-source --curl_libraries='-Wl,-rpath /usr/local/lib -lcurl'
pm2 kill


const { Curl, curly } = require("node-libcurl");
process.env.CURL_IMPERSONATE_HEADERS = "yes";
Curl.defaultUserAgent = null;
curly.defaultUserAgent = null;
const sessionCurl = curly.create();


thanks for keeping this lib up to date !

**Comment by AlexRevin** [comment]
A lot easier way with pre-combiled binaries

Mind the architecture of your docker environment and latest lib version in the url

```
WORKDIR /tmp/curl-lib
RUN wget --no-check-certificate https://github.com/yifeikong/curl-impersonate/releases/download/v0.7.0/libcurl-impersonate-v0.7.0.x86_64-linux-gnu.tar.gz \
  && tar zxvf libcurl-impersonate-v0.7.0.x86_64-linux-gnu.tar.gz \
  && cp libcurl-impersonate-chrome.so* /usr/local/lib \
  && echo "/usr/local/lib/libcurl-impersonate-chrome.so" >> /etc/ld.so.preload \
  && ldconfig /etc/ld.so.conf.d

WORKDIR /app
COPY package.json package-lock.json test.js ./
RUN npm rm --save node-libcurl
RUN npm install --save node-libcurl --no-cache --force --build-from-source --curl_libraries='-Wl,-rpath /usr/local/lib -lcurl-impersonate-chrome'
```

**Comment by bonald** [comment]
```

const { Curl,curly } = require('node-libcurl');

process.env.CURL_IMPERSONATE_HEADERS = 1
Curl.defaultUserAgent = null;
curly.defaultUserAgent = null;

process.env.CURL_IMPERSONATE = 'chrome124';

console.log(Curl.getVersion());

( async () => {
	const r= await curly.get('http://httpbin.io/headers');
	console.log(r.data);
})()
```
fixed

**Comment by lexiforest** [comment]
Changed my mind, see https://github.com/lexiforest/impers
