### ISSUE TITLE
Release files for arm/aarch are not generated correctly

### ISSUE THREAD

**Issue by yifeikong** [yifeikong/curl-impersonate#32]
Some bug must be introduced in https://github.com/yifeikong/curl-impersonate/compare/v0.6.0b7...v0.6.0b8

**Comment by bjia56** [comment]
What's the issue with the generated files? Might be related to the manylinux changes I made

**Comment by bjia56** [comment]
I can look into it as well

**Comment by bjia56** [comment]
I recommend reverting #30 and #14 for now and see if the binaries build properly. Not sure why the arm/aarch64 emulated builds are dropping those binaries, I can reproduce it with a manual build inside the container.

**Comment by bjia56** [comment]
Ok I see part of the issue - in x86_64, curl configuration reports this line:
```
2024-01-04T09:55:36.5448671Z   Build libcurl:    Shared=yes, Static=yes
```
whereas for arm:
```
2024-01-19T09:02:26.7690837Z   Build libcurl:    Shared=no, Static=yes
```
Testing a fix here: https://github.com/bjia56/curl-impersonate/pull/3

**Comment by bjia56** [comment]
For arm, the container is missing devtoolset-10-binutils. I'll need to build that from source.

**Comment by yifeikong** [comment]
It seems that the libcurl files are correct now, but the curl binaries are still too small.

**Comment by bjia56** [comment]
I can take another look at it in the next few days
