### ISSUE TITLE
Add fingerprints for Edge 120

### ISSUE THREAD

**Issue by rjenk22** [yifeikong/curl-impersonate#33]
Hello,

Would it be possible for you to add support for Edge 120 as a supported browser emulation?

Thank you much in advance for your consideration.

**Comment by yifeikong** [comment]
From the readme:

> Chromium-based browsers all share the same fingerprints, except for the User-Agent header and sec-ch-ua-platform header. They will not be updated unless this assumption changed. Use your own header if you need to impersonate Edge, Chrome Android etc.

**Comment by rjenk22** [comment]
I understand that but if I want to use this with your curl_cffi as an easy way to impersonate the browser, how would I have an option for impersonating edge120 since its not here in this repository? 

Will I need to fork this and create my own version that supports it?
