### ISSUE TITLE
Export windows building target

### ISSUE THREAD

**Issue by yifeikong** [yifeikong/curl-impersonate#4]
Maybe we should build natively with VC, not mingw?

**Comment by yifeikong** [comment]
Useful references:

1. https://everything.curl.dev/build/windows

It seems that you can not configure ECH with `winbuild`. We will have to use mingw as always.

**Comment by T-256** [comment]
it seems only `libcurl-impersonate` added for windows build. did you forget add it for `curl-impersonate` binary?
