### ISSUE TITLE
请求升级curl到8.9.1

### ISSUE THREAD

**Issue by gleox** [yifeikong/curl-impersonate#75]
我在调用libcurl的curl_multi_socket_action时出现NULL错误。我看到有Issue提到是libcurl自身的BUG，升级到8.9.1版本可能解决这个问题。我已尝试fork仓库自行处理，通过简单的替换libcurl版本号，不能够平滑升级，请帮助我升级libcurl到8.9.1版本。

参考Issues:

- [socket_function callbacks for unrelated sockets that are never removed #14280](https://github.com/curl/curl/issues/14280)
- [异常持续高 CPU 占用 #1100](https://github.com/fcitx/fcitx5/issues/1100#issuecomment-2264353698)

**Comment by yifeikong** [comment]
看起来只有 8.9.0 有这个问题啊，我们目前是基于 8.7.1，应该和这个不是一个问题吧？

**Comment by gleox** [comment]
我用官方的8.9.1版本测试了，还是一样的NULL错误，看来是我接口调用的问题。我自己再排查下，谢谢。

**Comment by jskorlol** [comment]
Would you be so kind as to share how you used it?
